apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: test-postgres
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /usr/local/pgsql/data

